const products=[
 {id:1,name:'Ripple ceramic vase',category:'Home',price:1290,image:'https://images.unsplash.com/photo-1612196808214-b8e1d6145a8c?auto=format&fit=crop&w=700&q=80',tag:'NEW'},
 {id:2,name:'Everyday linen shirt',category:'Style',price:1899,image:'https://images.unsplash.com/photo-1620799140408-edc6dcb6d633?auto=format&fit=crop&w=700&q=80',tag:'BESTSELLER'},
 {id:3,name:'Mellow desk lamp',category:'Home',price:2450,image:'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?auto=format&fit=crop&w=700&q=80',tag:'NEW'},
 {id:4,name:'Pocket noise-cancel buds',category:'Tech',price:3299,image:'https://images.unsplash.com/photo-1606220945770-b5b6c2c55bf1?auto=format&fit=crop&w=700&q=80',tag:'TRENDING'},
 {id:5,name:'Sunday ritual candle',category:'Wellness',price:850,image:'https://images.unsplash.com/photo-1602874801006-e26b6df27e2d?auto=format&fit=crop&w=700&q=80',tag:'FAVOURITE'},
 {id:6,name:'Soft form tote',category:'Style',price:1490,image:'https://images.unsplash.com/photo-1594223274512-ad4803739b7c?auto=format&fit=crop&w=700&q=80',tag:'NEW'},
 {id:7,name:'Daily greens tumbler',category:'Wellness',price:990,image:'https://images.unsplash.com/photo-1602143407151-7111542de6e8?auto=format&fit=crop&w=700&q=80',tag:'EASY GIFT'},
 {id:8,name:'The little hosting set',category:'Gifts',price:2190,image:'https://images.unsplash.com/photo-1603199506016-b9a594b593c0?auto=format&fit=crop&w=700&q=80',tag:'GIFTABLE'}
];
let cart=JSON.parse(localStorage.getItem('shopnest-cart')||'[]');let currentCategory='All';
const grid=document.querySelector('#productGrid');const money=v=>'₹'+v.toLocaleString('en-IN');
function renderProducts(){const term=document.querySelector('#searchInput').value.toLowerCase();const shown=products.filter(p=>(currentCategory==='All'||p.category===currentCategory)&&(!term||p.name.toLowerCase().includes(term)||p.category.toLowerCase().includes(term)));grid.innerHTML=shown.length?shown.map(p=>`<article class="product-card"><div class="product-image"><img src="${p.image}" alt="${p.name}" loading="lazy"><button class="heart ${cart.some(x=>x.id===p.id&&x.liked)?'liked':''}" data-like="${p.id}" aria-label="Add ${p.name} to wishlist">♡</button><span class="tag">${p.tag}</span></div><div class="product-info"><h3>${p.name}</h3><div class="product-meta"><span>${p.category}</span><strong>${money(p.price)}</strong></div><button class="text-button add-to-bag" data-id="${p.id}">Add to bag +</button></div></article>`).join(''):'<p class="empty-state">Nothing found in this edit. Try another search.</p>';}
function save(){localStorage.setItem('shopnest-cart',JSON.stringify(cart));updateBagCount();}
function updateBagCount(){const count=cart.reduce((sum,p)=>sum+(p.qty||1),0);document.querySelector('#bagCount').textContent=count;document.querySelector('#drawerCount').textContent=count;}
function renderBag(){const items=document.querySelector('#bagItems');const productsInCart=cart.filter(x=>!x.liked);items.innerHTML=productsInCart.length?productsInCart.map(item=>`<div class="bag-row"><img src="${item.image}" alt="${item.name}"><div><h3>${item.name}</h3><p>${money(item.price)} · Qty ${item.qty||1}</p><button class="remove" data-remove="${item.id}">Remove</button></div></div>`).join(''):'<p class="empty-state">Your bag is waiting for something lovely.</p>';const total=productsInCart.reduce((sum,p)=>sum+p.price*(p.qty||1),0);document.querySelector('#bagTotal').textContent=money(total);updateBagCount();}
function openPanel(id){document.querySelector('#overlay').hidden=false;document.querySelector('#'+id).classList.add('open')||null;if(id==='bagDrawer')renderBag();}
function closePanel(id){document.querySelector('#'+id).classList.remove('open');if(!document.querySelector('.drawer.open'))document.querySelector('#overlay').hidden=true;}
grid.addEventListener('click',e=>{const add=e.target.closest('.add-to-bag');const like=e.target.closest('[data-like]');if(add){const item=products.find(p=>p.id===+add.dataset.id);const existing=cart.find(p=>p.id===item.id&&!p.liked);if(existing)existing.qty=(existing.qty||1)+1;else cart.push({...item,qty:1});save();showToast('Added to your bag');}if(like){const item=products.find(p=>p.id===+like.dataset.like);const existing=cart.find(p=>p.id===item.id&&p.liked);if(existing)cart=cart.filter(p=>p!==existing);else cart.push({...item,liked:true});save();renderProducts();showToast(existing?'Removed from wishlist':'Saved to wishlist');}});
document.querySelectorAll('.category').forEach(btn=>btn.addEventListener('click',()=>{document.querySelector('.category.active').classList.remove('active');btn.classList.add('active');currentCategory=btn.dataset.category;renderProducts();}));
document.querySelector('.search-toggle').addEventListener('click',()=>{document.querySelector('#searchBar').classList.toggle('open');document.querySelector('#searchInput').focus();});document.querySelector('#closeSearch').addEventListener('click',()=>document.querySelector('#searchBar').classList.remove('open'));document.querySelector('#searchInput').addEventListener('input',renderProducts);document.querySelector('#bagButton').addEventListener('click',()=>openPanel('bagDrawer'));document.querySelector('#accountButton').addEventListener('click',()=>{document.querySelector('#overlay').hidden=false;document.querySelector('#loginModal').hidden=false;});document.querySelector('#overlay').addEventListener('click',()=>{closePanel('bagDrawer');document.querySelector('#loginModal').hidden=true;});document.querySelectorAll('[data-close]').forEach(btn=>btn.addEventListener('click',()=>{const id=btn.dataset.close;if(id==='loginModal'){document.querySelector('#loginModal').hidden=true;document.querySelector('#overlay').hidden=true}else closePanel(id);}));document.querySelector('#bagItems').addEventListener('click',e=>{if(e.target.dataset.remove){cart=cart.filter(p=>p.id!==+e.target.dataset.remove||p.liked);save();renderBag();}});document.querySelector('#checkoutButton').addEventListener('click',()=>showToast(cart.length?'Checkout is ready for you':'Your bag is empty'));
document.querySelector('#phoneForm').addEventListener('submit',e=>{e.preventDefault();const phone=document.querySelector('#phone').value;if(!/^\d{10}$/.test(phone)){document.querySelector('#loginMessage').textContent='Please enter a valid 10-digit number.';return}document.querySelector('#phoneForm').hidden=true;document.querySelector('#otpForm').hidden=false;document.querySelector('#loginMessage').textContent='OTP sent securely to +91 '+phone.slice(0,2)+'••••••'+phone.slice(-2);});document.querySelector('#otpForm').addEventListener('submit',e=>{e.preventDefault();if(document.querySelector('#otp').value==='2468'){document.querySelector('#loginModal').hidden=true;document.querySelector('#overlay').hidden=true;showToast('Welcome to your nest');}else document.querySelector('#loginMessage').textContent='That code is not correct. Please try again.';});document.querySelector('#resendOtp').addEventListener('click',()=>showToast('A new code has been requested'));document.querySelector('#newsletterForm').addEventListener('submit',e=>{e.preventDefault();document.querySelector('#newsletterMessage').textContent='You are on the list. See you soon.';e.target.reset();});document.querySelector('#viewAll').addEventListener('click',()=>{currentCategory='All';document.querySelector('.category.active').classList.remove('active');document.querySelector('[data-category="All"]').classList.add('active');renderProducts();document.querySelector('#shop').scrollIntoView({behavior:'smooth'});});function showToast(text){const toast=document.querySelector('#toast');toast.textContent=text;toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),2400)}renderProducts();updateBagCount();
